--Function that returns certain discount applied to a flight  

CREATE OR REPLACE FUNCTION GET_REDUCED_PRICE (
FLIGHT IN BOOKINGS.FLIGHT_NUMBER%TYPE,
DISC_TITLE IN DISCOUNTS.DISC_ID%TYPE) 
RETURN NUMBER 
IS
FLIGHT_PRICE FLIGHTS.BASE_PRICE%TYPE := 0;
DISC_QUANT DISCOUNTS.PERCENTAGE%TYPE := 0;
BEGIN
SELECT BASE_PRICE INTO FLIGHT_PRICE
FROM FLIGHTS WHERE FLIGHT_NO = FLIGHT;
IF SQL%FOUND THEN
    SELECT PERCENTAGE INTO DISC_QUANT
    FROM DISCOUNTS WHERE DISC_ID = DISC_TITLE;
    IF DISC_QUANT = NULL THEN
        RETURN FLIGHT_PRICE;
    END IF;
    RETURN (FLIGHT_PRICE * (100 - DISC_QUANT) / 100);
ELSE 
    DBMS_OUTPUT.PUT_LINE('This flight does not exist.');
    RETURN 0;
END IF;
END;

--Tests
SET SERVEROUTPUT ON
BEGIN
  DBMS_OUTPUT.PUT_LINE(GET_REDUCED_PRICE('AT404', 'FREQUENT'));
  DBMS_OUTPUT.PUT_LINE(GET_REDUCED_PRICE('RY900', 'STUDENT'));
  DBMS_OUTPUT.PUT_LINE(GET_REDUCED_PRICE('ET340', 'W-VETERAN'));
  DBMS_OUTPUT.PUT_LINE(GET_REDUCED_PRICE('ES922', 'FREQUENT'));
  DBMS_OUTPUT.PUT_LINE(GET_REDUCED_PRICE('IB887', '-'));
END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE(ROUND(DBMS_RANDOM.VALUE() * 100));
END;
/



--Function that shuffles seat number on 2nd class clients
--for a selected flight (assuming seats 1 to 20 are reserved for 1st class
CREATE OR REPLACE FUNCTION SHUFFLE_SEATS_FLIGHT (
    FLIGHT_N IN BOOKINGS.FLIGHT_NUMBER%TYPE)
    RETURN NUMBER
    IS
    CUR SYS_REFCURSOR;
    TMP_CLIENT BOOKINGS%ROWTYPE;
    COUNTER NUMBER := 0;
    BEGIN
        GETCLIENTSOFFLIGHTCURSOR(FLIGHT_N, CUR);
        LOOP
            FETCH CUR INTO TMP_CLIENT;
            EXIT WHEN CUR%NOTFOUND;
            IF TMP_CLIENT.SEAT_NUMBER > 20 THEN
                UPDATE BOOKINGS 
                SET SEAT_NUMBER = ROUND(DBMS_RANDOM.VALUE() * 100)
                WHERE PASSENGER_ID = TMP_CLIENT.PASSENGER_ID AND
                      FLIGHT_NUMBER = TMP_CLIENT.FLIGHT_NUMBER;
                
                COUNTER := COUNTER + 1;
            END IF;
        END LOOP;
        CLOSE CUR;
        RETURN COUNTER;
    END;
    
--Tests
    SET SERVEROUTPUT ON;
    BEGIN
      DBMS_OUTPUT.PUT_LINE('count: ' || SHUFFLE_SEATS_FLIGHT('RY900'));
      DBMS_OUTPUT.PUT_LINE('count: ' || SHUFFLE_SEATS_FLIGHT('KL237'));
      DBMS_OUTPUT.PUT_LINE('count: ' || SHUFFLE_SEATS_FLIGHT('ES922'));
    END;
    
