--Nationalities table creation

CREATE TABLE NATIONALITIES (
  SHORT_NAME VARCHAR2(3 BYTE) NOT NULL, 
  COUNT NUMBER DEFAULT 0, 
  FULL_NAME VARCHAR2(20 BYTE) NOT NULL
) LOGGING TABLESPACE SYSTEM PCTFREE 10 PCTUSED 40 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;
CREATE UNIQUE INDEX NATIONALITIES_PK ON NATIONALITIES (SHORT_NAME ASC) LOGGING TABLESPACE SYSTEM PCTFREE 10 INITRANS 2 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOPARALLEL;
ALTER TABLE 
  NATIONALITIES 
ADD 
  CONSTRAINT NATIONALITIES_PK PRIMARY KEY (SHORT_NAME) USING INDEX NATIONALITIES_PK ENABLE;


--Passenger table creation

  CREATE TABLE PASSENGERS (
  FIRST_NAME VARCHAR2(20 BYTE), 
  LAST_NAME VARCHAR2(20 BYTE), 
  ID NUMBER NOT NULL, 
  AGE NUMBER, 
  NATIONALITY VARCHAR2(3 BYTE), 
  MONEY_SPENT NUMBER DEFAULT 0
) LOGGING TABLESPACE SYSTEM PCTFREE 10 PCTUSED 40 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;
CREATE UNIQUE INDEX PASSENGERS_PK ON PASSENGERS (ID ASC) LOGGING TABLESPACE SYSTEM PCTFREE 10 INITRANS 2 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOPARALLEL;
ALTER TABLE 
  PASSENGERS 
ADD 
  CONSTRAINT PASSENGERS_PK PRIMARY KEY (ID) USING INDEX PASSENGERS_PK ENABLE;
ALTER TABLE 
  PASSENGERS 
ADD 
  CONSTRAINT FK_NATION FOREIGN KEY (NATIONALITY) REFERENCES NATIONALITIES (SHORT_NAME) ENABLE;


--Airlines table creation

CREATE TABLE AIRLINES (
  NAME VARCHAR2(20 BYTE) NOT NULL, 
  COUNTRY VARCHAR2(20 BYTE), 
  PHONE_NUMBER NUMBER
) LOGGING TABLESPACE SYSTEM PCTFREE 10 PCTUSED 40 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;
CREATE UNIQUE INDEX AIRLINES_PK ON AIRLINES (NAME ASC) LOGGING TABLESPACE SYSTEM PCTFREE 10 INITRANS 2 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOPARALLEL;
ALTER TABLE 
  AIRLINES 
ADD 
  CONSTRAINT AIRLINES_PK PRIMARY KEY (NAME) USING INDEX AIRLINES_PK ENABLE;
ALTER TABLE 
  AIRLINES 
ADD 
  CONSTRAINT FK_NATION_AIRLINE FOREIGN KEY (COUNTRY) REFERENCES NATIONALITIES (SHORT_NAME) ENABLE;

--Airports table creation

  CREATE TABLE AIRPORTS (
  NAME VARCHAR2(3 BYTE) NOT NULL, 
  FULL_NAME VARCHAR2(45 BYTE), 
  CITY VARCHAR2(20 BYTE), 
  COUNTRY VARCHAR2(20 BYTE)
) LOGGING TABLESPACE SYSTEM PCTFREE 10 PCTUSED 40 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;
CREATE UNIQUE INDEX AIRPORTS_PK ON AIRPORTS (NAME ASC) LOGGING TABLESPACE SYSTEM PCTFREE 10 INITRANS 2 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOPARALLEL;
ALTER TABLE 
  AIRPORTS 
ADD 
  CONSTRAINT AIRPORTS_PK PRIMARY KEY (NAME) USING INDEX AIRPORTS_PK ENABLE;
ALTER TABLE 
  AIRPORTS 
ADD 
  CONSTRAINT FK_COUNTRY_AIRPORT FOREIGN KEY (COUNTRY) REFERENCES NATIONALITIES (SHORT_NAME) ENABLE;

  --Flights table creation

  CREATE TABLE FLIGHTS (
  FLIGHT_NO VARCHAR2(20 BYTE) NOT NULL, 
  BOARDING_TIME VARCHAR2(5 BYTE), 
  DESTINATION VARCHAR2(20 BYTE), 
  ORIGIN VARCHAR2(20 BYTE), 
  AIRLINE VARCHAR2(20 BYTE), 
  PLANE_MODEL VARCHAR2(20 BYTE), 
  BASE_PRICE NUMBER DEFAULT 0
) LOGGING TABLESPACE SYSTEM PCTFREE 10 PCTUSED 40 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;
CREATE UNIQUE INDEX FLIGHTS_PK ON FLIGHTS (FLIGHT_NO ASC) LOGGING TABLESPACE SYSTEM PCTFREE 10 INITRANS 2 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOPARALLEL;
ALTER TABLE 
  FLIGHTS 
ADD 
  CONSTRAINT FLIGHTS_PK PRIMARY KEY (FLIGHT_NO) USING INDEX FLIGHTS_PK ENABLE;
ALTER TABLE 
  FLIGHTS 
ADD 
  CONSTRAINT FK_AIRLINE FOREIGN KEY (AIRLINE) REFERENCES AIRLINES (NAME) ENABLE;
ALTER TABLE 
  FLIGHTS 
ADD 
  CONSTRAINT FK_AIRPORT_DEST FOREIGN KEY (DESTINATION) REFERENCES AIRPORTS (NAME) ENABLE;
ALTER TABLE 
  FLIGHTS 
ADD 
  CONSTRAINT FK_AIRPORT_ORIGIN FOREIGN KEY (ORIGIN) REFERENCES AIRPORTS (NAME) ENABLE;





--Discounts table creation

CREATE TABLE DISCOUNTS (
  DISC_ID VARCHAR2(9 BYTE) NOT NULL, 
  PERCENTAGE NUMBER
) LOGGING TABLESPACE SYSTEM PCTFREE 10 PCTUSED 40 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;
CREATE UNIQUE INDEX DISCOUNTS_PK ON DISCOUNTS (DISC_ID ASC) LOGGING TABLESPACE SYSTEM PCTFREE 10 INITRANS 2 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOPARALLEL;
ALTER TABLE 
  DISCOUNTS 
ADD 
  CONSTRAINT DISCOUNTS_PK PRIMARY KEY (DISC_ID) USING INDEX DISCOUNTS_PK ENABLE;

  
  --Bookings table creation
  
CREATE TABLE BOOKINGS (
  PASSENGER_ID NUMBER NOT NULL, 
  FLIGHT_NUMBER VARCHAR2(20 BYTE) NOT NULL, 
  FINAL_PRICE NUMBER, 
  SEAT_NUMBER NUMBER
) LOGGING TABLESPACE SYSTEM PCTFREE 10 PCTUSED 40 INITRANS 1 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;
CREATE UNIQUE INDEX BOOKINGS_PK ON BOOKINGS (
  PASSENGER_ID ASC, FLIGHT_NUMBER ASC
) LOGGING TABLESPACE SYSTEM PCTFREE 10 INITRANS 2 STORAGE (
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS UNLIMITED FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT
) NOPARALLEL;
ALTER TABLE 
  BOOKINGS 
ADD 
  CONSTRAINT BOOKINGS_PK PRIMARY KEY (PASSENGER_ID, FLIGHT_NUMBER) USING INDEX BOOKINGS_PK ENABLE;
ALTER TABLE 
  BOOKINGS 
ADD 
  CONSTRAINT FK_FLIGHT_NUMBER FOREIGN KEY (FLIGHT_NUMBER) REFERENCES FLIGHTS (FLIGHT_NO) ENABLE;
ALTER TABLE 
  BOOKINGS 
ADD 
  CONSTRAINT FK_PASSENGER_ID FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGERS (ID) ENABLE;

  
  
  

  
  
  
