--Nationalities table creation

  CREATE TABLE "SYS"."NATIONALITIES" 
   (	"SHORT_NAME" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"COUNT" NUMBER DEFAULT 0, 
	"FULL_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "NATIONALITIES_PK" PRIMARY KEY ("SHORT_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--Passenger table creation

  CREATE TABLE "SYS"."PASSENGERS" 
   (	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(20 BYTE), 
	"ID" NUMBER NOT NULL ENABLE, 
	"AGE" NUMBER, 
	"NATIONALITY" VARCHAR2(3 BYTE), 
	 CONSTRAINT "PASSENGERS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "CLIENT_NATIONALITY" FOREIGN KEY ("NATIONALITY")
	  REFERENCES "SYS"."NATIONALITIES" ("SHORT_NAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  --Flights table creation

  CREATE TABLE "SYS"."FLIGHTS" 
   (	"FLIGHT_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BOARDING_TIME" VARCHAR2(5 BYTE), 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"ORIGIN" VARCHAR2(20 BYTE), 
	"AIRLINE" VARCHAR2(20 BYTE), 
	"PLANE_MODEL" VARCHAR2(20 BYTE), 
	"BASE_PRICE" NUMBER DEFAULT 0, 
	 CONSTRAINT "FLIGHTS_PK" PRIMARY KEY ("FLIGHT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FLIGHT_FK_AIRPORT_ORIGIN" FOREIGN KEY ("ORIGIN")
	  REFERENCES "SYS"."AIRPORTS" ("NAME") ENABLE, 
	 CONSTRAINT "FLIGHT_FK_AIRPORT_DEST" FOREIGN KEY ("DESTINATION")
	  REFERENCES "SYS"."AIRPORTS" ("NAME") ENABLE, 
	 CONSTRAINT "FLIGHT_FK_AIRLINE" FOREIGN KEY ("AIRLINE")
	  REFERENCES "SYS"."AIRLINES" ("NAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

--Airlines table creation

  CREATE TABLE "SYS"."AIRLINES" 
   (	"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"PHONE_NUMBER" NUMBER, 
	 CONSTRAINT "AIRLINES_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "AIRLINES_FK_NAT" FOREIGN KEY ("COUNTRY")

    
    
    
    REFERENCES "SYS"."NATIONALITIES" ("SHORT_NAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


--Airports table creation

  CREATE TABLE "SYS"."AIRPORTS" 
   (	"NAME" VARCHAR2(3 BYTE) NOT NULL ENABLE, 
	"FULL_NAME" VARCHAR2(45 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"COUNTRY" VARCHAR2(20 BYTE), 
	 CONSTRAINT "AIRPORTS_PK" PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "AIRPORT_FK_NAT" FOREIGN KEY ("COUNTRY")
	  REFERENCES "SYS"."NATIONALITIES" ("SHORT_NAME") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


--Discounts table creation

  CREATE TABLE "SYS"."DISCOUNTS" 
   (	"DISC_ID" VARCHAR2(9 BYTE) NOT NULL ENABLE, 
	"PERCENTAGE" NUMBER, 
	 CONSTRAINT "DISCOUNTS_PK" PRIMARY KEY ("DISC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
  --Bookings table creation
  
CREATE TABLE bookings
  (
     passenger_id  NUMBER NOT NULL,
     flight_number VARCHAR2(20 byte) NOT NULL,
     final_price   NUMBER,
     seat_number   NUMBER
  ) logging TABLESPACE SYSTEM PCTFREE 10 PCTUSED 40 INITRANS 1 STORAGE ( INITIAL
65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS unlimited FREELISTS 1 FREELIST GROUPS
1 buffer_pool DEFAULT ) NOCOMPRESS no inmemory noparallel;

CREATE UNIQUE INDEX bookings_pk
  ON bookings (passenger_id ASC, flight_number ASC)
logging TABLESPACE SYSTEM PCTFREE 10 INITRANS 2 STORAGE ( INITIAL 65536 NEXT
1048576 MINEXTENTS 1 MAXEXTENTS unlimited FREELISTS 1 FREELIST GROUPS 1
buffer_pool DEFAULT ) noparallel;

ALTER TABLE bookings
  ADD CONSTRAINT bookings_pk PRIMARY KEY ( passenger_id, flight_number ) USING
  INDEX bookings_pk ENABLE;

ALTER TABLE bookings
  ADD CONSTRAINT fk_flight_number FOREIGN KEY ( flight_number ) REFERENCES
  flights ( flight_no ) ENABLE;

ALTER TABLE bookings
  ADD CONSTRAINT fk_passenger_id FOREIGN KEY ( passenger_id ) REFERENCES
  passengers ( id ) ENABLE; 
  
  
  
  ---Flights table Creation
  
  
  CREATE TABLE "SYS"."FLIGHTS" 
   (	"FLIGHT_NO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BOARDING_TIME" VARCHAR2(5 BYTE), 
	"DESTINATION" VARCHAR2(20 BYTE), 
	"ORIGIN" VARCHAR2(20 BYTE), 
	"AIRLINE" VARCHAR2(20 BYTE), 
	"PLANE_MODEL" VARCHAR2(20 BYTE), 
	"BASE_PRICE" VARCHAR2(20 BYTE) DEFAULT 0, 
	 CONSTRAINT "FLIGHTS_PK" PRIMARY KEY ("FLIGHT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  
  
  
  
  
