CREATE OR REPLACE TRIGGER UPDATE_MONEY_SPENT
AFTER INSERT
   ON BOOKINGS
   FOR EACH ROW
BEGIN
    UPDATE PASSENGERS 
    SET MONEY_SPENT = MONEY_SPENT + :NEW.FINAL_PRICE
    WHERE ID = :NEW.PASSENGER_ID;
END;

CREATE OR REPLACE TRIGGER UPDATE_NATIONALITY_COUNT_INSERT
AFTER INSERT
   ON PASSENGERS
   FOR EACH ROW
BEGIN
    UPDATE NATIONALITIES 
    SET COUNT = COUNT + 1
    WHERE SHORT_NAME = :NEW.NATIONALITY;
END;

CREATE OR REPLACE TRIGGER UPDATE_NATIONALITY_COUNT_DELETE
AFTER DELETE
   ON PASSENGERS
   FOR EACH ROW
BEGIN
    UPDATE NATIONALITIES 
    SET COUNT = COUNT - 1
    WHERE SHORT_NAME = :OLD.NATIONALITY;
END;

